### ISSUE TITLE
Search Phone Directory

### ISSUE THREAD

**Issue by laurensius** [laurensius/SmartAirport_Backend#2]
Hello @sugiantoaziz , 
Mohon dibantu untuk buat API untuk proses search Phone.
Untuk ketenruan SBB :
- parameter input cukup 'name' (Merujuk pada nama instansi di tabel phone_dir)
- pada model gunakan query where. (where name like '**%**name**%**') sehingga akan menampilkan hasil search instansi dengan nama yg memiliki string **name** 
- format output seperti yang lainnya (JSON)

Happy Coding and Thank you!

_untuk info detail message aja yah_

**Comment by sugiantoaziz** [comment]
done, gan... periksa lagi... belum tes ke DB.

**Comment by laurensius** [comment]
OK. mantap. Terima kasih. :+1: 

Nantikan issues yang lainnya :smile:
