### ISSUE TITLE
Tourism REST

### ISSUE THREAD

**Issue by laurensius** [laurensius/SmartAirport_Backend#4]
Hello....
untuk ubah fitur search tourism. Jika saat ini search hanya by name (nama tempat wisata), mka untuk perubahannya adalah sbb : 
- untuk seach nya berupa name,category, city 
- sehingga function menjadi search(key,value), misal search(name.ipukan) atau search(category,food) dll

Kerjakan selagi senggang saja. jika ada kendala atau tidak dapat dihandle harap. kirim saya pesan, 
Thank you.

**Comment by sugiantoaziz** [comment]
on progress, mang...

**Comment by sugiantoaziz** [comment]
Done. 
API: /api/tourism_get_by_any/key_param/val_param

**Comment by laurensius** [comment]
OK. Checked. Complete!
Thank you!
